VoltAgent/voltagent

- website/src/components/navbar/index.tsx
This PR removes an unnecessary `hover` modifier from the `group-hover:translate-x-[-80%]` class. The `hover` was redundant as `group-hover` already triggers the effect when the parent group is hovered.
> Removed extra hover in translate-x

- website/blog/2025-04-23-multi-agent-llm/index.md
- website/src/components/blog-widgets/GitHubExampleLink.tsx
I added example code repo link widget for better navigation.
> feat: add GitHubExampleLink component

- website/docusaurus.config.ts
- website/plugins/gurubase/index.js
In the Voltagent [Docs](https://voltagent.dev/docs/) endpoint, you will now see an **Ask AI** button powered by [Gurubase](https://github.com/Gurubase/gurubase).
Gurubase has indexed the Voltagent documentation as well as key parts of the codebase (specifically the `examples/` and `packages/` folders), allowing users to ask natural language questions and get instant, AI-powered answers based on the official content.
fixes (issue)
> feat(docs): add gurubase Ask AI button

- examples/with-composio-mcp/.env.example
- examples/with-composio-mcp/.gitignore
- examples/with-composio-mcp/README.md
- examples/with-composio-mcp/package.json
- examples/with-composio-mcp/src/index.ts
- examples/with-composio-mcp/tsconfig.json
Currently, VoltAgent has examples for various integrations but lacks a specific example for integrating with Composio's Model Context Protocol (MCP) server, which would allow agents to access and interact with various third-party services through a unified interface.
Added a new example `with-composio-mcp` that demonstrates:
- How to configure `MCPConfiguration` for an HTTP-based Composio MCP server
- How to connect VoltAgent to third-party services like Gmail, Google Calendar, and Google Drive
- How to leverage Composio's managed authentication for seamless integration
- How to customize permissions for specific actions and data your agent can access
The example includes a comprehensive README with step-by-step instructions for …
> feat: add new example "with-composio-mcp"

- .changeset/chore-core-dedupe.md
- packages/core/package.json
- pnpm-lock.yaml
Currently, there is a dependency on the latest `@hono/node-server`, `@hono/node-ws` and the old `hono@3`, the first two of which depend on the latest hono, resulting in an unnecessary increase in size.
Updating Hono to the latest version will no longer have two Hono installations.
> chore(core): use latest hono to avoid duplicate dependencies

- .changeset/fifty-plums-think.md
- packages/google-ai/package.json
- packages/google-ai/src/index.spec.ts
- packages/google-ai/src/index.ts
- packages/google-ai/src/utils/schema_helper.spec.ts
- packages/google-ai/src/utils/schema_helper.ts
- pnpm-lock.yaml
- Added support for object generation based of schema in google-ai provider
- Bumped @voltagent/core package from 0.1.6 to 0.1.7
- Bumped  @google/genai package  to 0.10.0 
I had to copy over and modify a zod to json schema utility from official SDK package since that was not exported.
> feat(google-ai): Add support for structed object generation and streaming

- .changeset/twelve-lies-fold.md
- packages/core/package.json
- packages/core/src/server/api.routes.ts
- packages/core/src/server/api.ts
- packages/core/src/server/index.ts
- packages/core/src/server/types.ts
- pnpm-lock.yaml
- website/docs/api/overview.md
- website/sidebars.ts
- Integrated `@hono/zod-openapi` and `@hono/swagger-ui` to provide interactive API documentation.
- Documented the following core endpoints with request/response schemas, parameters, and examples:
- `GET /agents`: List all registered agents.
- `POST /agents/{id}/text`: Generate text response.
- `POST /agents/{id}/stream`: Stream text response (SSE).
- `POST /agents/{id}/object`: Generate object response (Note: Requires backend update to fully support JSON Schema input).
- `POST /agents/{id}/stream-object`: Stream object response (SSE) (Note: Requires backend update to fully support JSON Schema input).
- Added `/doc` endpoint serving the OpenAPI 3.1 specification in JSON format.
- Added `/ui` endpoint serving the interactive …
> feat: integrate OpenAPI documentation and enhance API routes

- .changeset/empty-coins-teach.md
- packages/voice/src/providers/elevenlabs/index.ts
> fix(voice): fix stream handling in ElevenLabs provider

- .changeset/moody-eagles-invite.md
- examples/with-groq-ai/src/index.ts
- packages/core/package.json
- packages/core/src/agent/index.ts
- packages/core/src/server/api.routes.ts
- packages/core/src/server/api.ts
- packages/google-ai/src/index.spec.ts
- packages/google-ai/src/index.ts
- packages/groq-ai/src/index.spec.ts
- packages/groq-ai/src/index.ts
- packages/vercel-ai/src/index.ts
- packages/xsai/package.json
- packages/xsai/src/index.spec.ts
- packages/xsai/src/index.ts
- pnpm-lock.yaml
**API & Providers:** Standardized message content format for array inputs.
- The API (`/text`, `/stream`, `/object`, `/stream-object` endpoints) now strictly expects the `content` field within message objects (when `input` is an array) to be either a `string` or an `Array` of content parts (e.g., `[{ type: 'text', text: '...' }]`).
- The previous behavior of allowing a single content object (e.g., `{ type: 'text', ... }`) directly as the value for `content` in message arrays is no longer supported in the API schema. Raw string inputs remain unchanged.
- Provider logic (`google-ai`, `groq-ai`, `xsai`) updated to align with this stricter definition.
> chore: update dependencies and enhance API functionality

- website/src/components/console/index.tsx
> feat(console): enhance Console component with live demo link 

- .changeset/cruel-jobs-arrive.md
- packages/google-ai/src/index.ts
- packages/google-ai/src/types.ts
- packages/google-ai/src/utils/function-calling.ts
- packages/google-ai/src/utils/schema_helper.ts
- The GoogleGenAIProvider does not support function call execution.
- There is no support for configuring tools or utility functions for Google SDK integration.
- Adds support for function call execution on the GoogleGenAIProvider.
- Enables the provider to handle and execute function calls.
- Introduces tool configuration options and utility functions to facilitate integration with the Google SDK.
- Implements support for parallel function calling, allowing multiple functions to 
be called and executed concurrently.
Here is an screenshot of the Google Agent using tools and running on the Developer Console.
> feat(google-ai): add function calling support for Google SDK integration

- .changeset/new-otters-turn.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- website/docs/agents/context.md
Currently, the `userContext` within an agent's `OperationContext` is primarily isolated to that specific agent's operation. There is no direct mechanism for a supervisor agent to automatically pass its `userContext` to sub-agents when delegating tasks. Sub-agents operate with their own fresh `userContext` unless context is manually passed through tool arguments, which can be cumbersome.
This PR introduces the capability for `userContext` to be seamlessly propagated from a supervisor agent to its sub-agents. 
Key changes include:
- `AgentOptions`, `PublicGenerateOptions`, and `InternalGenerateOptions` now accept an optional `userContext` (Map).
- When a sub-agent operation is initiated (e.g., via `delegate_task`), the …
> feat: enhance userContext functionality across agent operations

- website/docs/agents/overview.md
this PR fixes #120 
fixes (issue)
I checked throughout all the documentation to see if this issue repeats, but it only appears in agents/overview.md.
> fix(docs): the createTool function example on the agents/overview page is not using the correct option prop 

- .changeset/weak-zoos-sell.md
- packages/google-ai/src/index.ts
- packages/google-ai/src/types.ts
- packages/google-ai/src/utils/function-calling.ts
The `generateText` method in the `GoogleGenAIProvider` does not include the `toolCalls` and the `toolResults` as part of the response.
The `generateText` method now includes two optional fields in its response object:
-   `toolCalls`: An array containing the function calls requested by the model (if any).
-   `toolResults`: An array containing the results of executing those function calls (if any).
This provides more visibility into the interaction when tools are used.
fixes #115 
The new fields (`toolCalls` and `toolResults`) are optional and will only be populated when function calling is triggered. Type definitions have been updated accordingly.
> feat(google-ai): include tool calls and results in generateText response

- .changeset/all-breads-behave.md
- packages/core/src/agent/history/index.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/open-telemetry/index.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/events/index.ts
- packages/core/src/index.ts
- packages/core/src/internal/dev-logger.ts
- packages/core/src/mcp/client/index.spec.ts
- packages/core/src/mcp/client/index.ts
- packages/core/src/mcp/registry/index.ts
- packages/core/src/memory/in-memory/index.spec.ts
- packages/core/src/memory/in-memory/index.ts
- packages/core/src/memory/libsql/index.ts
- packages/core/src/memory/manager/index.ts
- packages/core/src/telemetry/client/index.ts
- packages/core/src/tool/index.ts
- packages/core/src/tool/manager/index.ts
- packages/core/src/tool/reasoning/tools.ts
- packages/core/src/tool/toolkit.ts
- packages/core/src/utils/internal/dev-logger/index.spec.ts
- packages/core/src/utils/internal/dev-logger/index.ts
- packages/core/src/utils/update/index.ts
`console.<func>` are polluting server logs when using VoltAgent
replaced with a logger that omits logs when `NODE_ENV` is NOT `development`
> chore(core): remove logging via `console.log` in favor of dev logger that won't pollute production logs

- examples/with-anthropic/README.md
- examples/with-composio-mcp/README.md
- examples/with-zapier-mcp/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/create-voltagent-app/package.json
- packages/create-voltagent-app/templates/base/README.md.template
- packages/google-ai/package.json
- packages/groq-ai/package.json
- packages/langfuse-exporter/package.json
- packages/postgres/package.json
- packages/sdk/package.json
- packages/supabase/package.json
- packages/vercel-ai-exporter/README.md
- packages/vercel-ai-exporter/package.json
- packages/vercel-ai/package.json
- packages/voice/package.json
- packages/xsai/package.json
- pnpm-lock.yaml
- website/docs/community/contributing.md
- website/src/components/ops/Deployment.tsx
follow up of https://github.com/VoltAgent/voltagent/pull/213
Added updates to documentation and `@types/node` that were previously missed. Node 18 support should now be fully dropped in all relevant places.
fixes (issue)
> chore: update documentation and types to drop Node.js 18 support

- .changeset/polite-wings-enter.md
- examples/with-vercel-ai/src/index.ts
- packages/anthropic-ai/src/index.ts
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/providers/base/types.ts
- packages/core/src/agent/types.ts
- packages/core/src/index.ts
- packages/core/src/server/api.ts
- packages/core/src/utils/async-iterable-stream/index.spec.ts
- packages/core/src/utils/async-iterable-stream/index.ts
- packages/core/src/utils/internal/test/index.ts
- packages/google-ai/src/index.ts
- packages/groq-ai/src/index.ts
- packages/xsai/src/index.spec.ts
- packages/xsai/src/index.ts
Currently the `streamObject` and `streamText` return a `ReadableStream` which is not iterable.
`streamObject` and `streamText` return an `AsyncIterableStream` that can be iterated safely:
```typescript
const result = agent.streamText();
for await (const chunk of result.textStream) {
console.log(chunk);
}
```
in addition it standardizes the core primitive or textStream and objectStream so its the same across the board, instead of dependent on the provider.
> feat: migrate the provider streams to `AsyncIterableStream`

- .changeset/streamable-http-transport.md
- packages/core/package.json
- packages/core/src/mcp/client/index.spec.ts
- packages/core/src/mcp/client/index.ts
- packages/core/src/mcp/types.ts
- pnpm-lock.yaml
- website/docs/agents/mcp.md
VoltAgent's MCP client only supports SSE transport for HTTP connections. The `type: "http"` configuration uses the legacy SSEClientTransport from @modelcontextprotocol/sdk v1.10.1.
- Upgraded @modelcontextprotocol/sdk to v1.12.1 to access StreamableHTTPClientTransport
- Modified existing `type: "http"` to use automatic transport selection with streamable HTTP → SSE fallback
- Added two new transport types:
- `type: "sse"` - Force SSE transport only
- `type: "streamable-http"` - Force streamable HTTP transport only
- Existing HTTP configurations work unchanged via automatic fallback
- Updated documentation with transport types section and examples
fixes [#246](https://github.com/VoltAgent/voltagent/issues/246)
The implementation …
> feat(core): add streamable HTTP transport support for MCP client

- .changeset/twelve-cats-repair.md
- packages/core/src/index.ts
- packages/core/src/server/api.ts
- packages/core/src/server/index.ts
- packages/core/src/types.ts
- website/docs/api/overview.md
No option to disable Swagger UI
By default:
In development (NODE_ENV !== 'production'): Swagger UI is enabled
In production (NODE_ENV === 'production'): Swagger UI is disabled
// Enable Swagger UI even in production
`startServer({ enableSwaggerUI: true });`
// Disable Swagger UI even in development
`startServer({ enableSwaggerUI: false });`
fixes (issue)
#241
> feat(core): add config to disable swagger ui

- .changeset/puny-bikes-laugh.md
- packages/postgres/src/index.ts
Currently in the postgres migration method, there is the following line `level TEXT DEFAULT "INFO",`, however "INFO" here is interpreted as a table name, throwing an error
```
[PostgresStorage] Error initializing database: error: cannot use column reference in DEFAULT expression
at /Users/wouter/Desktop/ADSR/agent/node_modules/pg/lib/client.js:545:17
at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
length: 121,
severity: 'ERROR',
code: '0A000',
detail: undefined,
hint: undefined,
position: '467',
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'parse_expr.c',
line: …
```
> fix(postgres): fix default value being interpreted as column name

- .changeset/silver-cobras-cheer.md
- packages/postgres/src/index.ts
updated the offending fields with single quotes in order to be interpreted as string literals
fixes (#316)
> fix(postgres): fields being identified as identifiers

- .changeset/slow-zoos-speak.md
- packages/core/src/memory/manager/index.spec.ts
- packages/core/src/memory/manager/index.ts
When `memory: false` is set, conversation memory and user messages should be disabled, but history storage and timeline events should continue working. Previously, both conversation memory and history storage were being disabled together.
fixes (issue)
> fix: separate conversation memory from history storage when memory: false

- .changeset/fine-queens-train.md
- packages/core/src/agent/types.ts
fixes (issue)
- https://discord.com/channels/1361559153780195478/1390900532276629575
> fix: export PromptContent type to resolve "cannot be named" TypeScript error

- .changeset/funny-chicken-jump.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- website/docs/agents/context.md
- website/docs/agents/overview.md
The userContext option passed to the Agent constructor was being silently discarded. This fix:
- Adds defaultUserContext property to store constructor-provided context
- Updates initializeHistory to use constructor context as fallback
- Ensures dynamic values (instructions, model, tools) can access constructor context
- Adds tests for constructor userContext functionality
- Updates documentation to explain both constructor and execution context usage
The `userContext` option in the Agent constructor is accepted by the TypeScript interface but completely ignored in the implementation. Users must pass `userContext` on every execution call (generateText, streamText, etc.) instead of being able to set a default context when creating …
> fix(core): store and use userContext from Agent constructor

- .changeset/cute-lands-type.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/memory/manager/index.spec.ts
- packages/core/src/memory/manager/index.ts
- website/docs/agents/memory/overview.md
Fixes issue where MemoryManager always defaulted to LibSQLStorage for history memory even when Agent was configured with InMemoryStorage. The historyMemory parameter existed in MemoryManager constructor but was not exposed through AgentOptions, preventing users from configuring history memory storage.
- Add historyMemory parameter to AgentOptions interface
- Update Agent constructor to pass historyMemory to MemoryManager
- Add comprehensive tests for historyMemory configuration
- Maintain backward compatibility with existing code
VoltAgent can fail with default configuration in environments with read-only filesystems (like AWS Lambda) with the error:
```
Error: ConnectionFailed("Unable to open connection to local database …
```
> fix(core): add historyMemory option to Agent configuration

- .changeset/dirty-papers-glow.md
- packages/vercel-ui/src/messages/convert-to-ui.spec.ts
- packages/vercel-ui/src/messages/convert-to-ui.ts
Currently Volt is passing an empty string (most likely in core). Patching in the vercel-ui to prevent breaking as a unique ID is needed.
fixes passing an empty string
> fix: generate an ID if missing to make sure we don't have an ID of empty string

- .changeset/cold-results-heal.md
- packages/docs-mcp/src/tools.ts
Currently, **@voltagent/docs-mcp** only includes files that match a specific set of relative paths within each example directory when generating output from the `get_voltagent_example` tool.
**LIST OF FILES INCLUDED IN THE CURRENT BEHAVIOR**
<blockquote><details><summary>CLICK TO EXPAND</summary>
```sh
examples/base/package.json
examples/base/README.md
examples/base/src/index.ts
examples/github-repo-analyzer/package.json
examples/github-repo-analyzer/README.md
examples/github-repo-analyzer/src/index.ts
examples/sdk-trace-example/package.json
examples/sdk-trace-example/README.md
examples/sdk-trace-example/src/index.ts
examples/with-anthropic/package.json
examples/with-anthropic/README.md
examples/with-anthropic/src/index.ts …
```
> feat(docs-mcp): dynamically discover example files

- .changeset/shy-kiwis-bet.md
- packages/core/src/workflow/chain.spec.ts
- packages/core/src/workflow/core.spec.ts
- packages/core/src/workflow/internal/state.ts
> fix: add back `workflow.run` result due to bad state mgmt

- packages/core/src/agent/agent.spec.ts
- packages/core/src/agent/providers/base/types.ts
- packages/core/src/index.ts
- packages/internal/package.spec.ts
- packages/internal/src/utils/async-iterable-stream.spec.ts
- packages/internal/src/utils/async-iterable-stream.ts
- packages/internal/src/utils/index.ts
- pnpm-lock.yaml
Currently the async-iterable util is nested in core but we need to use elsewhere and shouldn't be buried there.
n/a
Big question is should it be exported from `@voltagent/core` or should we just change all the providers that use it.
No changelog due to no public change
> chore: move async-iterable utils out of core

- .changeset/fix-anthropic-json-formatting.md
- packages/anthropic-ai/src/index.spec.ts
- packages/anthropic-ai/src/index.ts
The generateObject method in the Anthropic AI provider returns invalid JSON responses because the AI model wraps JSON responses in markdown code blocks (e.g., \json ... `). This causes JSON parsing to fail, resulting in errors when trying to parse the response.
Root Cause: The system prompt was not explicit enough about the expected response format, leading the AI to format responses as markdown which included:
- Wrapping JSON in \json` code blocks
- Adding explanatory text before or after the JSON
- Using markdown formatting that broke JSON parsing
Enhanced the system prompt in both generateObject and streamObject methods with explicit instructions that prevent markdown formatting:
```const systemPrompt = …
```
> fix(anthropic-ai): improve generateObject JSON formatting with explicit system prompt

- .changeset/new-mammals-divide.md
- packages/core/src/workflow/core.spec.ts
- packages/core/src/workflow/internal/types.ts
- packages/core/src/workflow/steps/and-all.ts
- packages/core/src/workflow/steps/and-race.ts
When you use `andAll` or `andRace` in `createWorkflows` it bypasses the inferred results and just uses the passed in `INPUT` type.
fixes: it uses the correct inferred type.
BONUS: We can now have a proper tuple (feature less fix) if you use the `as const` keyword in your steps:
```ts
andAll({
...config
steps: [...] as const // will show as tuple
})
```
> fix: Skipping inferred types `andRace` and `andAll` in `createWorkflow`

- .changeset/tangy-houses-repeat.md
- packages/core/src/workflow/core.spec.ts
- packages/core/src/workflow/core.ts
- packages/core/src/workflow/internal/utils.spec.ts
- packages/core/src/workflow/internal/utils.ts
- packages/core/src/workflow/stream.ts
- packages/core/src/workflow/types.ts
- website/docs/workflows/streaming.md
Related to #589 
- Workflow stream is not compatible with `useChat` react hook.
- You can pipe raw SSE events like workflow-start into useChat, but useChat only understands the AI SDK UI Message Stream protocol (the “text-start / text-delta / …” chunks and data-* parts that the SDK generates).
- Workflows can now stream data as UIMessage chunks, ensuring compatibility with useChat hook. 
- Converts raw workflow events into `data-*` prefixed UIMessages in the `toUIMessageStreamResponse` function.
- UIMessages can be streamed for workflows by server via `streamResult.toUIMessageStreamResponse()` 
fixes #589 
All workflow events types will be prefixed with `data-*` to follow [AI SDK …
> feat(core): enable workflow to stream UIMessages to conform with useChat
