VoltAgent/voltagent

- llms.txt
as you know, standard docs aren't enough for llms. sometimes it does not fit context of LLMs or  too verbose to introduce details. as voltagent is relatively new repo + LLMs do not know a lot about that, using llms.txt for the ones coding with codex/cursor/windsurf is inevitable. i've created this one for myself
this `llms.txt` goes beyond links, embedding core voltagent context: architecture, component roles (agent, managers), feature mechanics (tools, memory, rag, sub-agents, voice, mcp, providers), design rationale, key workflows, and integrated code examples. it directly addresses limitations of fragmented info, aiming to significantly improve ai accuracy and reduce hallucination when reasoning about voltagent.
**this pr delivers:**
*   **internalized context:** explains concepts like …
> `llms.txt` – a self-contained knowledge base for llms, designed for deep framework understanding

- website/blog/2025-04-23-multi-agent-llm/index.md
- website/src/components/blog-widgets/LlmChoiceHelper.tsx
I've added the blog post:  2025-04-23-multi-agent-llm
> feat: add '2025-04-23-multi-agent-llm'

- .changeset/quick-chairs-smell.md
- packages/cli/package.json
- packages/core/package.json
- packages/create-voltagent-app/package.json
- packages/supabase/package.json
- packages/vercel-ai/package.json
- packages/voice/package.json
- packages/xsai/package.json
This will reduce the size by excluding the `src` folder when publishing.
> chore(packages): add exports, clean files

- website/blog/2025-04-27-ai-agents-frameworks/index.md
- website/blog/2025-04-27-building-voltagent/index.md
> feat: add "2025-04-27-ai-agents-frameworks"

- website/src/components/hero/index.tsx
I updated the click scope for the word in hero. Also, added a little animation on hover.
> feat(hero): enhance Hero component with heart icon

- website/blog/2025-04-26-peaka-mcp-voltagent/index.md
> fix: correct wording in blog post on

- .changeset/chore-core-exports.md
- packages/core/package.json
> chore(core): add exports

- website/src/components/navbar/index.tsx
- website/src/components/navbar/styles.module.css
> docs(landing): update navbar

- website/docs/agents/overview.md
- [x ] The commit message follows our guidelines: https://voltagent.dev/docs/community/contributing/#commit-convention
fixes (issue)
> docs: Update overview.md typo

- examples/with-zapier-mcp/.gitignore
- examples/with-zapier-mcp/README.md
- examples/with-zapier-mcp/package-lock.json
- examples/with-zapier-mcp/package.json
- examples/with-zapier-mcp/src/index.ts
- examples/with-zapier-mcp/tsconfig.json
VoltAgent previously lacked a dedicated example for integrating with a Zapier Model Context Protocol (MCP) server, which enables agents to interact with third-party services through Zapier’s unified API.
This PR introduces a new example, `with-zapier-mcp`, which demonstrates:
- How to configure `MCPConfiguration` for an HTTP-based Zapier MCP server
- How to connect VoltAgent to third-party services available via Zapier
- How to use environment variables for secure configuration
- How to leverage Zapier’s unified interface for tool access
The example includes a comprehensive, step-by-step README. Notably, the README was authored collaboratively in this chat session to ensure it matches the actual code (`src/index.ts`), providing …
> feat: with-zapier-mcp

- website/docs/providers/xsai.md
> docs(providers/xsai): update multi-modal support section

- .changeset/grumpy-spoons-wonder.md
- packages/google-ai/src/index.ts
- packages/google-ai/src/types.ts
- The GoogleGenAIProvider does not support function call execution on streamText
- The streaming process would continue without pausing for function execution
- No handling of tool calls and tool results in the streaming process
- Added full support for function calling within the streamText method.
- The stream processing detect function calls and executes them while collecting results
- Handles tool events through onChunk and onStepFinish callbacks
- It preserves the original streaming behavior when no function calls are present.
The implementation preserves the original streaming while adding function calling capabilities.
> feat(google-ai): enhance streamText functionality with function call handling

- .changeset/silent-plants-clap.md
- packages/core/src/tool/index.ts
- [] Related issue(s) linked
- [] Tests for the changes have been added
- [] Docs have been added / updated
Fixed the issue https://github.com/voltagent/voltagent/issues/112
> fix(core): export createToolkit

- website/docusaurus.config.ts
… Product Hunt launch
fixes (issue)
> feat(announcement-bar): update announcement content

- website/blog/2025-05-13-llm-observability/index.md
- website/src/components/blog-widgets/LlmIssueSpotter.tsx
- website/src/components/blog-widgets/ObservabilityPrioritizer.tsx
I added LLM observability post.
> feat(blog): add beginner guide on LLM observability

- website/docusaurus.config.ts
> fix(announcement-bar): update announcement

- website/blog/2025-05-16-multimodal-rag/index.md
- website/src/components/ZoomableMermaid.tsx
- website/src/components/blog-widgets/MultimodalQueryExplorer.tsx
- website/src/components/blog-widgets/ZoomableMermaid.module.css
- website/src/components/blog-widgets/ZoomableMermaid.tsx
> docs(blog): add multi modal post

- README.md
- website/blog/2025-05-16-multimodal-rag/index.md
- website/blog/2025-05-17-llmafactory/index.md
- website/src/components/blog-widgets/LlamaFactoryNavigator.tsx
> docs(blog): add llm factory post

- website/blog/2025-05-19-llm-orchestration/index.md
- website/src/components/blog-widgets/OrchestrationComponentExplorer.tsx
- website/src/components/blog-widgets/OrchestrationStarterKitAdvisor.tsx
> docs(blog): add llm observability post 

- llms.txt
- website/blog/2025-05-21-vercel-ai-sdk/index.md
- website/src/components/blog-widgets/IntegrationScenarioSelector.tsx
- website/src/components/blog-widgets/VercelAiModelComparison.tsx
- website/src/components/blog-widgets/VercelAiSdkFeatureMatcher.tsx
- website/src/components/blog-widgets/VercelAiVoltAgentWorkflow.tsx
> docs(blog): add Vercel AI post

- website/blog/2025-05-26-llm-agents/index.md
- website/src/components/blog-widgets/AgentArchitectureExplorer.tsx
- website/src/components/blog-widgets/AgentCapabilitiesMatrix.tsx
> docs(blog): add LLM post

- .changeset/spicy-moons-wave.md
- packages/core/src/agent/index.ts
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- website/docs/agents/subagents.md
> feat(core): Add `purpose` to allow for longer, multi-line instructions for subagents, without overloading the supervisor <specialized_agents>

- .changeset/flat-badgers-rush.md
- examples/with-voice-xsai/src/index.ts
- examples/with-xsai/src/index.ts
- packages/voice/src/providers/xsai/index.ts
- packages/voice/src/providers/xsai/types.ts
- packages/xsai/src/index.spec.ts
- packages/xsai/src/index.ts
- website/docs/providers/xsai.md
- website/static/llms.txt
> fix(voice,xsai): rename XsAI, Xsai to XSAI

- website/docusaurus.config.ts
- website/src/theme/Layout/index.js
Show 2 footers
Show only 1 footer
fixes (issue)
> docs(website): remove duplicated footer

- packages/create-voltagent-app/biome.json
- packages/create-voltagent-app/package.json
- packages/create-voltagent-app/src/cli.ts
- packages/create-voltagent-app/src/project-creator.ts
- packages/create-voltagent-app/src/utils/analytics.ts
- packages/create-voltagent-app/src/utils/animation.ts
- packages/create-voltagent-app/src/utils/file-manager.ts
- packages/create-voltagent-app/src/utils/github.ts
`create-voltagent-app` package version of https://github.com/VoltAgent/voltagent/pull/203
fixes (issue)
> chore(create-voltagent-app): switch ESLint to Biome 

- packages/google-ai/biome.json
- packages/google-ai/package.json
- packages/google-ai/src/index.ts
- packages/google-ai/src/types.ts
- packages/google-ai/src/utils/function-calling.ts
`@voltagent/google-ai` package version of https://github.com/VoltAgent/voltagent/pull/203
fixes (issue)
> chore(google-ai): switch ESLint to Biome

- packages/vercel-ai/biome.json
- packages/vercel-ai/package.json
- packages/vercel-ai/src/index.ts
`vercel-ai` package version of #203
fixes (issue)
> chore(vercel-ai): switch ESLint to Biome 

- packages/xsai/biome.json
- packages/xsai/package.json
- packages/xsai/src/index.spec.ts
- packages/xsai/src/index.ts
`xsai` package version of https://github.com/VoltAgent/voltagent/pull/203
fixes (issue)
> chore(xsai): switch ESLint to Biome

- .changeset/all-bikes-spend.md
- .github/workflows/pull-request.yml
- examples/with-rag-chatbot/package.json
- package.json
- packages/cli/package.json
- packages/create-voltagent-app/package.json
- website/package-lock.json
- website/package.json
Sometimes things don’t work correctly with certain Node versions, so I think it’s a good idea to run CI with the LTS versions of Node.
fixes (issue)
> chore!: Drop Node.js v18

- examples/with-google-drive-mcp/client/biome.json
- examples/with-google-drive-mcp/client/eslint.config.js
- examples/with-google-drive-mcp/client/package.json
- examples/with-google-drive-mcp/client/src/App.tsx
- examples/with-google-drive-mcp/client/src/components/Layout.tsx
- examples/with-google-drive-mcp/client/src/components/LoginPage.tsx
- examples/with-google-drive-mcp/client/src/components/ProtectedRoute.tsx
- examples/with-google-drive-mcp/client/src/context/AuthContext.tsx
- examples/with-google-drive-mcp/client/src/main.tsx
- examples/with-google-drive-mcp/client/vite.config.ts
- examples/with-google-drive-mcp/server/biome.json
- examples/with-google-drive-mcp/server/package.json
- examples/with-google-drive-mcp/server/src/index.ts
- examples/with-google-drive-mcp/server/src/voltagent/index.ts
`examples/with-google-drive-mcp` package version of https://github.com/VoltAgent/voltagent/pull/203
fixes (issue)
> chore(with-google-drive-mcp): switch ESLint to Biome

- website/src/components/showcase/ProjectCard.tsx
- website/src/components/showcase/projects.json
- website/src/theme/ShowcaseProjectPage/index.tsx
> docs(showcase): add new showcases

- .changeset/cuddly-spoons-hammer.md
- .changeset/metal-maps-shout.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/providers/base/types.ts
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/index.ts
- packages/core/src/server/api.ts
- packages/vercel-ai/src/index.ts
- packages/vercel-ai/tsup.config.ts
- packages/xsai/src/index.ts
- pnpm-lock.yaml
- website/docs/agents/overview.md
https://github.com/user-attachments/assets/8306fe88-7c04-440e-aff3-11b74a49987b
fixes (issue)
> feat(core): add fullStream support for generative UIs

- .changeset/some-candies-arrive.md
- packages/google-ai/src/utils/schema_helper.spec.ts
- packages/google-ai/src/utils/schema_helper.ts
When running a subagents workflow, a zod error is thrown.
Subagents are created successfully and no zod error is thrown.
fixes #114
> fix(google-ai): fix zod errors on subagents workflow

- website/docusaurus.config.ts
- website/src/components/live-preview/index.tsx
- website/src/components/navbar/index.tsx
- website/src/components/supervisor-agent/workflow-code-example.tsx
- website/src/css/layout.css
… for better accessibility
I updated the navbar
> refactor(navbar): enhance mobile navigation

- .changeset/new-nails-live.md
- examples/base/.env.example
- examples/with-dynamic-parameters/.env.example
- examples/with-dynamic-parameters/.gitignore
- examples/with-dynamic-parameters/README.md
- examples/with-dynamic-parameters/package.json
- examples/with-dynamic-parameters/src/index.ts
- examples/with-dynamic-parameters/tsconfig.json
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/index.ts
- packages/core/src/server/api.routes.ts
- packages/core/src/server/api.ts
- pnpm-lock.yaml
- website/docs/agents/dynamic-agents.md
- website/docs/api/overview.md
- website/sidebars.ts
> feat: add dynamic agent parameters

- .changeset/mighty-ghosts-stop.md
- packages/cli/package.json
- packages/cli/src/commands/mcp.ts
- packages/cli/src/index.ts
- packages/cli/src/utils/mcp-config.ts
- packages/create-voltagent-app/src/cli.ts
- packages/create-voltagent-app/src/project-creator.ts
- packages/create-voltagent-app/src/types.ts
- packages/create-voltagent-app/src/utils/analytics.ts
- packages/create-voltagent-app/src/utils/mcp-config.ts
- packages/docs-mcp/.gitignore
- packages/docs-mcp/README.md
- packages/docs-mcp/biome.json
- packages/docs-mcp/package.json
- packages/docs-mcp/project.json
- packages/docs-mcp/src/index.ts
- packages/docs-mcp/src/server.ts
- packages/docs-mcp/tsconfig.json
- packages/docs-mcp/tsup.config.ts
- packages/docs-mcp/vitest.config.mts
- pnpm-lock.yaml
- website/docs/getting-started/mcp-docs-server.md
- website/sidebars.ts
> feat: add docs mcp

- .changeset/giant-dolls-check.md
- .changeset/witty-mammals-take.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
- website/docs/providers/google-ai.md
> fix: subagent task delegation system message handling for Google Gemini

- .changeset/upset-feet-stand.md
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
> fix(core): re-fix the role for a subagents task/prompt

- examples/with-hugging-face-mcp/.env.example
- examples/with-hugging-face-mcp/.gitignore
- examples/with-hugging-face-mcp/README.md
- examples/with-hugging-face-mcp/package.json
- examples/with-hugging-face-mcp/src/index.ts
- examples/with-hugging-face-mcp/tsconfig.json
- pnpm-lock.yaml
VoltAgent previously lacked a dedicated example for integrating with a Hugging Face Model Context Protocol (MCP) server, which enables agents to interact with various AI models and services hosted on Hugging Face Spaces.
This PR introduces a new example, `with-hugging-face-mcp`, which demonstrates:
- How to configure `MCPConfiguration` for connecting to Hugging Face's MCP server
- How to authenticate with Hugging Face using API tokens
- How to access various AI models hosted on Hugging Face Spaces
- How to handle multimodal interactions including image generation, text-to-speech, and vision tasks
The example includes a comprehensive, step-by-step README that explains how to set up and use the integration. The README was …
> feat: add hf mcp example

- examples/with-chroma/README.md
- examples/with-chroma/src/retriever/index.ts
- website/docs/rag/chroma.md
- website/docs/rag/overview.md
> fix: update chroma example

- CONSOLE.md
> docs(CONSOLE): enhance documentation

- website/src/components/footer/index.tsx
- website/src/pages/oss-friends.tsx
> feat:(oss-friends): add OSS friends page

- website/blog/2025-07-02-top-llm-observability/index.md
> docs(blog): add top llm pos

- .changeset/itchy-trees-shine.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/server/api.ts
- website/docs/api/overview.md
> feat: add abort signal support for operation cancellation

- .changeset/eighty-olives-sing.md
- packages/core/src/agent/index.spec.ts
- packages/core/src/agent/index.ts
- packages/core/src/agent/subagent/index.spec.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/events/types.ts
- packages/core/src/server/api.routes.ts
- website/docs/agents/overview.md
- website/docs/agents/subagents.md
- website/docs/api/overview.md
fixes (issue)
- #332 - It's fixes maxSteps configuration
> feat: add maxSteps option

- .changeset/grumpy-bars-turn.md
- packages/xsai/src/index.spec.ts
- packages/xsai/src/index.ts
> fix(xsai): xsai-tools-sent-undefined

- website/src/components/tutorial/TutorialLayout.tsx
- website/src/components/tutorial/TutorialNavbar.tsx
> refactor: streamline TutorialLayout and

- website/src/components/customers/customers.json
> docs(blog): add customer stories

- .changeset/major-teeth-stay.md
- packages/core/src/mcp/registry/index.ts
- packages/core/src/mcp/types.ts
No timeout input supported for users
Users can customize mcp client timeout
fixes (issue)
> MCPClient timeout support

- .changeset/sad-falcons-follow.md
- examples/with-workflow/src/index.ts
- packages/core/src/workflow/chain.spec.ts
- packages/core/src/workflow/context.ts
- packages/core/src/workflow/core.spec.ts
- packages/core/src/workflow/core.ts
- packages/core/src/workflow/index.ts
- packages/core/src/workflow/internal/types.ts
- packages/core/src/workflow/internal/utils.ts
- packages/core/src/workflow/steps/and-agent.ts
- packages/core/src/workflow/steps/and-all.ts
- packages/core/src/workflow/steps/and-race.ts
- packages/core/src/workflow/steps/and-tap.spec.ts
- packages/core/src/workflow/steps/and-tap.ts
- packages/core/src/workflow/steps/and-then.ts
- packages/core/src/workflow/steps/and-when.ts
- website/docs/workflows/execute-api.md
- website/docs/workflows/overview.md
- website/docs/workflows/steps/and-agent.md
- website/docs/workflows/steps/and-all.md
- website/docs/workflows/steps/and-race.md
- website/docs/workflows/steps/and-tap.md
- website/docs/workflows/steps/and-then.md
- website/docs/workflows/steps/and-when.md
- website/sidebars.ts
> feat: improve workflow execute API with context-based pattern

- website/blog/2025-07-20-llm-evaluation/index.md
- website/src/components/blog-widgets/EvaluationMethodRecommender.tsx
- website/src/components/blog-widgets/EvaluationMetricsComparison.tsx
> feat: add LLM evaluation blog post and related components

- website/blog/2025-07-23-llm-testing/index.md
> docs(blog): add testing post

- website/blog/2025-07-24-crew-ai/index.md
> docs(blog): add crew post

- .changeset/eight-webs-carry.md
- CHANGELOG.md
- packages/core/src/agent/agent.ts
- packages/core/src/tool/manager/index.spec.ts
- packages/core/src/tool/manager/index.ts
> fix: dynamic toolkit resolution and VoltOps UI visibility

- website/blog/2025-07-29-ts-ai-agent/index.md
I added ts ai agent framework post
> feat(blog): add new article on TypeScript AI Agent Framework - VoltAgent

- .changeset/puny-ads-arrive.md
- packages/core/src/index.ts
- packages/core/src/workflow/index.ts
> fix: expose `andWorkflow` for public use

- .changeset/agent-event-pagination.md
- packages/core/src/agent/agent.spec.ts
- packages/core/src/agent/agent.ts
- packages/core/src/agent/history/index.ts
- packages/core/src/events/index.spec.ts
- packages/core/src/events/index.ts
- packages/core/src/memory/in-memory/index.spec.ts
- packages/core/src/memory/in-memory/index.ts
- packages/core/src/memory/libsql/index.ts
- packages/core/src/memory/manager/index.spec.ts
- packages/core/src/memory/manager/index.ts
- packages/core/src/memory/types.ts
- packages/core/src/server/api.ts
- packages/postgres/src/index.spec.ts
- packages/postgres/src/index.ts
- packages/supabase/src/index.ts
> feat: optimize agent event history

- website/blog/2025-08-04-ai-agent-vs-chatbot/index.md
- website/src/components/blog-widgets/AgentChatbotComparison.tsx
> feat: add blog post comparing AI agents and chatbots

- .changeset/lucky-bears-share.md
- packages/core/src/agent/agent.spec.ts
- packages/core/src/agent/agent.ts
> feat: add userContext to logger context for better traceability

- .changeset/bright-foxes-dance.md
- .changeset/cool-teams-reply.md
- .changeset/fuzzy-lamps-sing.md
- packages/core/src/server/api.ts
- packages/core/src/utils/voltops-validation.ts
- packages/core/src/voltagent.ts
- packages/create-voltagent-app/templates/base/.env.template
- packages/create-voltagent-app/templates/base/index.ts.template
> feat: add easy voltops setup

- website/blog/2025-08-07-llm-guardrails/index.md
> docs(blog): add llm guardrails post

- .changeset/fix-abort-signal-propagation.md
- packages/core/src/agent/agent.spec.ts
- packages/core/src/agent/agent.ts
- packages/core/src/agent/hooks/index.ts
- packages/core/src/agent/providers/base/types.ts
- packages/core/src/agent/subagent/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/index.ts
- website/docs/agents/cancellation.md
- website/docs/agents/overview.md
- website/docs/agents/tools.md
- website/sidebars.ts
> fix: abort signal propagation to LLM providers for proper cancellation support

- .changeset/green-taxis-play.md
- packages/core/src/workflow/chain.spec.ts
- packages/core/src/workflow/chain.ts
- packages/core/src/workflow/context.ts
- packages/core/src/workflow/core.spec.ts
- packages/core/src/workflow/core.ts
- packages/core/src/workflow/internal/state.ts
- packages/core/src/workflow/internal/types.ts
- packages/core/src/workflow/internal/utils.ts
- packages/core/src/workflow/registry.ts
- packages/core/src/workflow/steps/and-agent.ts
- packages/core/src/workflow/stream.spec.ts
- packages/core/src/workflow/stream.ts
- packages/core/src/workflow/types.ts
- packages/core/src/workflow/usage-tracking.spec.ts
- website/docs/workflows/streaming.md
- website/sidebars.ts
> feat: add real-time stream support and usage tracking for workflows

- .changeset/three-garlics-brush.md
- packages/core/src/memory/in-memory/index.ts
> fix: inMemoryStorage timestamp field for VoltOps history display

- .changeset/khaki-ravens-stop.md
- examples/with-tools/src/index.ts
- packages/core/src/agent/agent.ts
- website/docs/agents/tools.md
… experience -
fixes (issue)
- #487
> feat: add addTools method and deprecate addItems - #487

- .changeset/ninety-animals-smell.md
- packages/supabase/src/memory.ts
> fix: resolve SupabaseClient ESM import error

- jog.yaml
> chore: integrate joggr

- website/blog/2025-08-22-n8n-pricing/index.md
> docs(blog): add n8n blog

- packages/core/src/voltagent.ts
> fix(next): Switch VoltOps to use `globalThis` instead of a local var to allow for bundling

- website/blog/2025-09-05-agents-brief/index.md
> feat: add AI Agent post VoltAgent

- website/blog/2025-09-08-vector-db/index.md
> docs(blog): add vector db post

- .changeset/forty-cycles-punch.md
- packages/core/src/agent/agent.ts
- packages/core/src/memory/index.ts
- packages/core/src/memory/manager/memory-manager.ts
- packages/core/src/memory/semantic-search.spec.ts
- website/docs/agents/memory/overview.md
- website/docs/agents/memory/semantic-search.md
> feat(core): semantic memory defaults and retrieval fixes

- .changeset/tough-jobs-brush.md
- packages/core/src/agent/agent-error.ts
- packages/core/src/agent/agent.spec-d.ts
- packages/core/src/agent/agent.ts
- packages/core/src/agent/errors/abort-error.spec-d.ts
- packages/core/src/agent/errors/abort-error.spec.ts
- packages/core/src/agent/errors/abort-error.ts
- packages/core/src/agent/errors/index.ts
- packages/core/src/agent/errors/voltagent-error.spec-d.ts
- packages/core/src/agent/errors/voltagent-error.spec.ts
- packages/core/src/agent/errors/voltagent-error.ts
- packages/core/src/agent/hooks/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/index.ts
- pnpm-lock.yaml
> chore: better error types (using base error)

- .changeset/green-bushes-hammer.md
- packages/core/src/agent/agent.ts
- website/docs/agents/overview.md
> feat: add experimental_output support for structured generation

- .changeset/purple-oranges-slide.md
- examples/with-subagents/src/index.ts
- packages/core/src/agent/open-telemetry/trace-context.ts
> fix: improve subagent tracing hierarchy and entity filtering

- .changeset/wicked-ways-draw.md
- packages/core/src/agent/subagent/index.ts
> fix: resolve subagent tool call/result pairing issue with Claude/Bedrock

- .changeset/calm-baboons-think.md
- docs/structure.md
- examples/with-tools/src/index.ts
- packages/core/src/agent/agent.ts
- packages/core/src/agent/conversation-buffer.spec.ts
- packages/core/src/agent/conversation-buffer.ts
- packages/core/src/agent/memory-persist-queue.spec.ts
- packages/core/src/agent/memory-persist-queue.ts
- packages/core/src/agent/memory-persistence.integration.spec.ts
- packages/core/src/utils/message-converter.spec.ts
- packages/core/src/utils/message-converter.ts
- website/docs/agents/memory/overview.md
- website/src/components/usecases/usecases.json
> fix: add ConversationBuffer + MemoryPersistQueue so tool calls, results

- .changeset/khaki-islands-try.md
- packages/core/src/agent/subagent/index.ts
> fix: resolve Zod v4 compatibility issue in delegate_task tool schema

- examples/with-tavily-search/.env.example
- examples/with-tavily-search/README.md
- examples/with-tavily-search/package.json
- examples/with-tavily-search/src/index.ts
- examples/with-tavily-search/src/tools.ts
- examples/with-tavily-search/tsconfig.json
- pnpm-lock.yaml
This PR adds a new example `with-tavily-search` that demonstrates how to integrate Tavily's advanced web search API with VoltAgent.
- **Web Search**: Real-time web search using Tavily API
- **Content Extraction**: Extract content from specific URLs  
- **AI-Powered Answers**: Comprehensive answers based on current web data
- **Flexible Configuration**: Search depth, domain filtering, result limits
- `examples/with-tavily-search/` - Complete example directory
- `src/tools.ts` - Tavily search and extract tools
- `src/index.ts` - Agent setup with search capabilities
- `README.md` - Comprehensive documentation
- `package.json` - Updated with correct VoltAgent versions
- `.env.example` - Environment variable template
1. `tavilySearchTool` - Advanced web search with AI answers
2. …
> Add Tavily Search Example

- .changeset/chilly-apes-agree.md
- .changeset/crazy-frogs-notice.md
- packages/core/src/agent/agent.spec-d.ts
- packages/core/src/agent/agent.spec.ts
- packages/core/src/agent/agent.ts
- packages/core/src/agent/hooks/index.spec.ts
- packages/core/src/agent/hooks/index.ts
- packages/core/src/agent/message-normalizer.spec.ts
- packages/core/src/agent/message-normalizer.ts
- packages/core/src/utils/message-converter.ts
- website/docs/agents/hooks.md
- website/docs/agents/prompts.md
> feat: introduce `onPrepareModelMessages` hook for message transformation

- .changeset/long-eyes-drive.md
- examples/with-working-memory/src/index.ts
- packages/core/src/agent/types.ts
- packages/core/src/memory/index.ts
- packages/core/src/memory/manager/memory-manager.ts
- packages/core/src/memory/types.ts
- packages/core/src/observability/adapters/in-memory-adapter.ts
- packages/core/src/observability/types.ts
- packages/libsql/src/observability-adapter.ts
- packages/server-core/src/edge.ts
- packages/server-core/src/handlers/__tests__/memory-observability.handlers.spec.ts
- packages/server-core/src/handlers/memory-observability.handlers.ts
- packages/server-core/src/handlers/observability.handlers.ts
- packages/server-core/src/index.ts
- packages/server-core/src/routes/definitions.ts
- packages/server-core/src/types/index.ts
- packages/server-core/src/types/observability-memory.ts
- packages/server-hono/src/routes/observability.ts
- packages/serverless-hono/src/routes.ts
- pnpm-lock.yaml
> feat: add memory observability

- CONSOLE.md
- website/docs/getting-started/quick-start.md
- website/observability/voltagent-framework.md
- website/src/pages/tutorial/introduction.tsx
Updated the logs respect to latest cli output.
> docs: update console logs after successfully voltagent server starts.

- examples/with-youtube-to-blog/.env.example
- examples/with-youtube-to-blog/.gitignore
- examples/with-youtube-to-blog/README.md
- examples/with-youtube-to-blog/package.json
- examples/with-youtube-to-blog/src/index.ts
- examples/with-youtube-to-blog/tsconfig.json
- pnpm-lock.yaml
- website/examples/youtube-to-blog.md
- website/src/data/tweets.json
- website/src/theme/ExampleProjectPage/index.tsx
> examples: add youtube agent example
